version: '2'
services:
  root:
    build: root
  
  years:
    build: years
    volumes:
      - /var/www/years
    read_only: true
  
  mandelbrot:
    build: mandelbrot
    volumes:
      - /var/www/mandelbrot
    read_only: true
    
  nginx:
    build: nginx
    depends_on:
      - years
      - mandelbrot
    volumes_from:
      - years
      - mandelbrot
    links:
      - root:root_typowriter
      - years:years_typowriter
      - mandelbrot:mandelbrot_typowriter
    ports:
      - "80:80"